# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test this action

on:
  push:
  workflow_dispatch:

jobs:
  test_the_action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: encryption test
        uses: ./ # Uses an action in the root directory
        id: pgp
        if: ${{ contains(env.PRIVATE_KEY, 'BEGIN') }}
        with:
          text: encryption test
          key: ${{ secrets.PUBLIC_KEY }}
          privateKey: ${{ secrets.PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      - name: signing test
        uses: ./ # Uses an action in the root directory
        id: pgp2
        if: ${{ contains(env.PRIVATE_KEY, 'BEGIN') }}
        with:
          text: signing test
          key: ${{ secrets.PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      - name: keyserver test
        uses: ./ # Uses an action in the root directory
        id: pgp3
        with:
          text: keyserver test
          keysource: keyserver
          keyserver: https://keys.openpgp.org
          key: 5B01AC37ECF039FD24F7434646A9E63BBC90F2D1
      - name: wkd test
        uses: ./ # Uses an action in the root directory
        id: pgp4
        with:
          text: wkd test
          keysource: wkd
          key: opliko.reg@protonmail.com
      - name: print results
        run: echo "output results - \n1. ${{ steps.pgp.outputs.encrypted-text }}\n2. ${{ steps.pgp2.outputs.encrypted-text }}\n3. ${{ steps.pgp3.outputs.encrypted-text }}\n4. ${{ steps.pgp4.outputs.encrypted-text }}\n"
